### ISSUE TITLE
Linter: Support global bears

### ISSUE THREAD

**Issue by sils** [coala/coala#2050]

**Comment by Makman2** [comment]
I'm planning a new parameter (maybe `kind` or `bear_base` or so), that you can set to `GlobalBear` (or explicitly to `LocalBear`, but this would be the default), and `@linter` rearranges the tool chain so that it receives the right params inside run and passes them to a slightly different version of `create_arguments` and `generate_config` (and maybe also `process_output`).

**Comment by NiklasMM** [comment]
@Makman2 are you still working on this? Otherwise I'd like to give this a go over the weekend.

**Comment by Makman2** [comment]
@NiklasMM go ahead :) If you have questions regarding the Linter, let me know, it's quite some code^^ :+1:

**Comment by Makman2** [comment]
@NiklasMM how is it going? :)

**Comment by NiklasMM** [comment]
I started looking at the code and it's a little more complex than I expected. I would still like to work on it, but have to find some time first ;)

**Comment by NiklasMM** [comment]
Got it! :+1: Will move it up in my imaginary prioritized todo list ;)

**Comment by NiklasMM** [comment]
@Makman2 sorry for the delay, but I've opened the PR now ;)
