### ISSUE TITLE
Shell autocompletion setup

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#2405]
I noticed that we have a doc to setup autocomplete - http://coala.readthedocs.io/en/latest/Users/Tutorials/Shell_Autocompletion.html

... if the user is capable of reading the doc, they probably won't need the autocomplete ;)

First off:
It would be nice to add this line to the ~/.profile rather than ~/.bashrc and ~/.zshrc
~/.profile is normally loaded in ~/.bashrc and ~/.zshrc if I'm not mistaken. Because ~/.profile is loaded in ssh too.

It would make sense to tell the user we're doing this and just add it. Basically make then "opt in" for autocomplete by default. (Only on linux of course)

**Comment by hypothesist** [comment]
During coala installation? Or have a separate `setup-coala-autocomplete` command that does this depending on the shell?

**Comment by AbdealiJK** [comment]
I was thinking during installation

**Comment by jayvdb** [comment]
@all3fox , as you did a lovely job with https://github.com/coala/coala/issues/2914 and convincing answer wrt https://github.com/coala/coala/issues/3887 , could you also decide how we proceed with this one.

**Comment by all3fox** [comment]
No-no-no, I would strongly advise against messing with the user's `.zshrc` or (maybe also) `.bashrc` file. For instance, arch users often go with the `zsh` configuration called `grml-zsh-config` because that is a nice shell they work in while installing archlinux (and then just stay with it). That config generates a `.zshrc` automatically and then asks you to provide your manual modifications in `.zshrc.local`

Bottomline, you never know if `.zshrc` is autogenerated or not and there probably are many similar corner-cases

As for `.profile`, `man zsh` tells us that file is sourced only for login shells and then this [unix stackexchange][1] answer tells two things:

1. Some shells (like `csh`) do not source it and others (probably unsupported by `argcomplete`) do source it, which may lead to errors reported at startup.
2. It is sourced by login shells, which is probably not what we want.

I do not know much about login shells and interactive shells, but I am against the `.profile` modification.

My opinion is that current way of making the user consciously modify their own shell file is best and does not need to be changed.

[1]: https://unix.stackexchange.com/a/46856/44624

**Comment by jayvdb** [comment]
@yukiisbored your thoughts?

**Comment by yukiisbored** [comment]
Same as @alisianoi. Modifying the user's shell rc/profile is a bad idea. The program should instruct the user not the other way around or give them the choice to let the program do it or to let them do it themselves.

Detecting if the file is generated or not just adds complexity to the program without a lot of benefits.
