### ISSUE TITLE
Fix typo: docs/Review: Continous -> Continuous

### ISSUE THREAD

**Issue by adtac** [coala/coala#2470]

**Comment by netman92** [comment]
ME

**Comment by anshuman73** [comment]
Hi, has this issue been solved with the aforementioned commit  -https://github.com/coala/coala/commit/514b216ae01227bc4ab655068aa582ac6cb579a4 ?

Infact, I cannot even find this file in the latest master branch.

If this issue is resolved, can it be closed ? Or if some work is required, I'll be happy to contribute

**Comment by sils1297** [comment]
CC @Adrianzatreanu

**Comment by Adrianzatreanu** [comment]
this is what happens when you dont label stuff..

yes, this is fixed and moved to another repo https://github.com/coala/documentation/blob/master/Developers/Review.rst
