### ISSUE TITLE
Plugin for Visual Studio Code

### ISSUE THREAD

**Issue by agauniyal** [coala/coala#2685]

**Comment by sils1297** [comment]
Hey @agauniyal thanks for reporting, I'm not sure if any of our developers use vscode - it should be pretty simple to get a basic plugin that uses coala-json or coala-format if they have proper facilities.

**Comment by Makman2** [comment]
renamed issue so it's easier to find

**Comment by Makman2** [comment]
From @gaocegege 
> Now coala has an [atom plugin](https://github.com/coala/coala-atom). We need a plugin for VS Code, too.
>
> ## Feature
>
> 1. Linter for supported languages.
> 2. Auto fix just like [coala/coala-atom](https://github.com/coala/coala-atom) does.
> 3. What features do you want? you could list them in the comment.
>
> ## Reference
>
> * [coala/coala-atom](https://github.com/coala/coala-atom)
> * [VS Code Extensibility Reference](https://code.visualstudio.com/docs/extensionAPI/overview)
> * [A Ruby Linter for VS Code](https://github.com/hoovercj/vscode-ruby-linter)

**Comment by Makman2** [comment]
From @gaocegege 
> #dibs
>
> This is a stand alone project. So I would create a new repo and transfer to coala when I finish the work :)
>
> https://github.com/gaocegege/coala-vscode

**Comment by gaocegege** [comment]
Now we get two approaches.

## Child Process

We could do the same things as [VS Code buit-in PHP extension](https://github.com/Microsoft/vscode/tree/master/extensions/php/src), create a child process to run coala every time we need it.

### Advantages

Easy to implement.

### Disadvantages

It's not a general implementation, just for VS Code.

### ETC

2017.2.11

## Language Server

[Language Server](https://github.com/Microsoft/language-server-protocol) is a protocol to integrate features like auto complete, goto definition, find all references and alike into the tool. The following diagram illustrates the communication between a tool and the language server.

![](https://github.com/Microsoft/language-server-protocol/raw/master/images/interaction-diagram.png)

### Advantages

I think Language Server Protocol(LSP) works for coala. VS Code, Eclipse IDE, Eclipse Che and other editors announced support for the protocol. So we could support those editors by one language server.

### Disadvantages

Because [there is no protocol implementation in python,](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations#sdks) we have to implement the protocol on our own. there is a [python-langserver](https://github.com/sourcegraph/python-langserver) powered by sourcegraph, maybe we could reference it.

### ETC

2017.03.XX

## 

WDYT, I think language server is better, but it takes more time. And I wanna to complete the project before GSoC begins. Or could I take this project as the GSoC project to apply for?

**Comment by sils** [comment]
LSP sounds better on long term

**Comment by gaocegege** [comment]
Yeah I think so, but I'm afraid I couldn't finish the work before 2017.03

**Comment by gaocegege** [comment]
It seems that the idea is not as difficult as I think, I could finish it before GSoC. 🤔

**Comment by gaocegege** [comment]
https://github.com/gaocegege/coala-langserver

The language server have been  partially completed.

## Done

1. push diagnostics to language client.

## TODO

1. update diagnostics when the text changed. ref https://github.com/gaocegege/coala-langserver/issues/1
2. support file events from vs code workspace.

![](https://github.com/gaocegege/coala-langserver/raw/master/docs/images/demo.png)

**Comment by sils** [comment]
Wohoa! This is awesome!

**Comment by gaocegege** [comment]
Now when vs code user save the file, coala will be run in a standalone process, and push the result to client in vs code asynchronously.

In the future, coala could be run every time code changes in the editor, but I'm afraid changes of code is frequently and the time spent on coala may be a little long.

I think maybe it's time to transfer ownership to coala, and deploy to vs code plugin market.

![](https://github.com/gaocegege/coala-langserver/raw/master/docs/images/demo.gif)

**Comment by sils** [comment]
Hey I gave you access to https://github.com/coala/coala-vs-code/ so we can make it official, this is super gorgeous!

**Comment by jayvdb** [comment]
Lets call this done, and create new issues for other requirements
