### ISSUE TITLE
codecov coverage down unexpectedly

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#2737]
Coverage lost on coala_main.py at line [#113](https://github.com/coala-analyzer/coala/blob/master/coalib/coala_main.py#L113)

**Comment by meetmangukiya** [comment]
cc @sils1297 @underyx

**Comment by Makman2** [comment]
can't see something dropped at `master` :O

**Comment by meetmangukiya** [comment]
@Makman2, @sils1297 witnessed the drop :/

**Comment by sils1297** [comment]
It's nondeterministic and seems to occur in rare cases so I think we should
look into it.

**Comment by meetmangukiya** [comment]
Do we need this now ? Or close it ?

**Comment by Makman2** [comment]
haven't see any flaw yet, reopen if you think it still occurs^^

**Comment by jayvdb** [comment]
Was this reported by the codecov github integration (i.e. rejecting a PR on github), or was this actual pytest coverage in Travis?

I suspect the former, in which case we wont know if it is still a bug, because we disabled that integration sometime around the time of this issue (but I could be a month off easily).

**Comment by meetmangukiya** [comment]
Yes, it was the codecov github integration
