### ISSUE TITLE
Update the latest stable version in the README

### ISSUE THREAD

**Issue by adtac** [coala/coala#2742]
I think it's 0.8.1 now.

**Comment by manthansharma** [comment]
I want to work on this issue

**Comment by sils1297** [comment]
Hey,

I think you have done two newcomer issues and it seems you're well acquainted with the workflow! That's awesome :)

We recommend to not do newcomer issues anymore because they take us more time to file than to fix them - let other newcomers can have a few as well. The next level for you are the [low difficulty issues](http://tinyurl.com/coala-low) - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

Cheers!

**Comment by sils1297** [comment]
@adtac why do we have that badge if it's not auto updating? Can we just remove that?

**Comment by adtac** [comment]
@sils1297 IMO we should mention the current version *somewhere* in the README. And I think a badge is a cool way for it to stand out. But I can't think of any way to auto-update it :(

**Comment by adtac** [comment]
We could update it during the series of commits we do for releases - release notes, README, VERSION, then push to PyPI.

**Comment by sils1297** [comment]
hm, maybe we can make a script for the release, shouldn't be too hard

**Comment by mgracer48** [comment]
can i work on this?

**Comment by sils1297** [comment]
Sure @mgracer48 !

**Comment by mgracer48** [comment]
So whats the task basically i need to do (change the version numbers? ) (make a script to change it easily?)

**Comment by sils1297** [comment]
The task here is just to change the version numbers indeed. If you want to
do something more challenging, add a release script somewhere ;) like
`.misc/release.py 0.8.1`, there's a script `.misc/adjust_version_number.py`
that you can reuse, it's already used in rultor, our merge bot; see
.rultor.yml.
