### ISSUE TITLE
NpmRequirement.is_installed fails with Ubuntu npm 1.1.4

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#2751]
On Ubuntu precise, `npm show nonexistent_package` prints a blank line and return exit code 0, so `NpmRequirement.is_installed` returns true for everything.

**Comment by sils1297** [comment]
CC @Adrianzatreanu

**Comment by fneu** [comment]
`npm show` is the wrong command here, since it looks up package information, independend of whether or not the package is installed [1]. It's behaviour for nonexistent packages is even irrelevant here.

IMO `NpmRequirement` should use `npm list` here [2]:

> This command will print to stdout all the versions of packages that are installed, as well as their dependencies, in a tree-structure.

I'm reworking cib at the moment anyway, so assigning myself.
Labelled unimportant for now since cib is not yet in shape.

[1]: https://docs.npmjs.com/cli/view
[2]: https://docs.npmjs.com/cli/ls

**Comment by sils1297** [comment]
@fneu but it's really critical to get cib into shape. It's relieving to know you're on cib, does @Adrianzatreanu know?

**Comment by jayvdb** [comment]
> npm show is the wrong command here, since it looks up package information, independend of whether or not the package is installed 

So that is a major bug?  There are a lot of bears using `NpmRequirement`, and I'm guessing that means they are not correctly reporting that the bear dependency is missing...?  Separate bug for that?

**Comment by Adrianzatreanu** [comment]
yes @sils1297 i know that he's working on it, im looking forward :)

**Comment by sils1297** [comment]
This is not a major bug because all the requirement classes are only used
in [cib](https://github.com/coala-analyzer/coala/#installation) which is
experimental. Still we want to make it production ready within few weeks
ideally so I'm super happy about your bug reports!

**Comment by jayvdb** [comment]
@fneu , in #2754 , you say 'Since 'npm' is not a locally installed package according to 'npm list',
the test had to be changed to make use of a mock, since we cannot rely
upon any one package always bein there.'

Doesnt the same apply for all the JS tools the bears are using.  i.e. `remark-cli` could be in the global install prefix, and therefore wont be in `npm list` ?
Sorry if I am mistaken; my knowledge of npm is quite low.

**Comment by fneu** [comment]
I'm by no means an expert on npm, but if I understand it correctly, just calling `npm list` without arguments lists all the packages it finds on the system. And there aren't many:

```
root@309a9d0be7f7:/# npm list
/
└── (empty)

root@309a9d0be7f7:/# echo $?
0
```
although it returns `0`, while trying a package that is not installed returns `1`.

```
root@309a9d0be7f7:/# npm list stuff
/
└── (empty)

root@309a9d0be7f7:/# echo $?
1
```

now:
```
root@309a9d0be7f7:/# npm install remark-cli

[output]

root@309a9d0be7f7:/# npm list
/
└─┬ remark-cli@2.0.0
  ├── markdown-extensions@1.1.0
  ├─┬ remark@6.0.1

[more output]

root@309a9d0be7f7:/# npm list remark-cli
/
└── remark-cli@2.0.0 

root@309a9d0be7f7:/# echo $?
0
```

I actually tried to put `self.assertTrue(NpmRequirement('').is_installed())` in the test but it failed, as well as `self.assertTrue(NpmRequirement(' ').is_installed())` (with a space)

`self.assertTrue(NpmRequirement('remark-cli').is_installed())` works locally, though, after installing the package, so that's how I came to my conclusion.

**Comment by jayvdb** [comment]
But does it work after
```
$ sudo  npm install -g remark-cli
```
(On tablet for a few hours)

**Comment by fneu** [comment]
no you were right, I answered and then read your question again, edited my comment

it does indeed not work, thanks for noticing.

but we can check for it with `npm list -g remark-cli`

So we can just check locally and globally and then look whether one of the checks succeeds

**Comment by fneu** [comment]
updated #2754
