### ISSUE TITLE
ConfigurationGathering.py: Missing method parameter in the docstring

### ISSUE THREAD

**Issue by raul1991** [coala/coala#2811]
Method name : gather_configuration is missing a parameter named arg_parser in the doc string.

**Comment by capellini** [comment]
I'd like to claim this.

**Comment by capellini** [comment]
Looks like @anu0012 already submitted a PR.  Looking at the PR, I would suggest at least adding the same description that's in `coalib/parsing/CliParsing.py` (i.e. `Instance of ArgParser that is used to parse none-setting arguments.`) to the docstring, rather than just including the parameter with no description.

I'll keep looking for other places where I could possibly help.

**Comment by sils1297** [comment]
Hi @capellini and @anu0012 ! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

@anu0012 ping us so we can assign you after accepting the org invitation.
@capellini feel free to leave review comments, that's highly encouraged. The PR is the right place to leave those comments :) Thanks a lot for your help.

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by capellini** [comment]
Hi @sils1297 -- thanks for the invite!  Indeed -- I'll put my comments in the PR. :+1:

**Comment by guptavaasu** [comment]
please assign me this issue!

**Comment by amrandahvur** [comment]
Assign me this

**Comment by sils** [comment]
Done.
