### ISSUE TITLE
Fix typo: bearlib/__init__.py : nondeterministic -> non-deterministic

### ISSUE THREAD

**Issue by Udayan12167** [coala/coala#2838]

**Comment by nikssardana** [comment]
Please assign this to me. Thanks!

**Comment by sils1297** [comment]
Hey,

it seems you're well acquainted with the workflow! That's awesome :)

We recommend to not do newcomer issues anymore because they take us more time to file than to fix them - let other newcomers can have a few as well. The next level for you are the [low difficulty issues](http://coala.io/low) - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

Cheers!

**Comment by nikssardana** [comment]
Ok. I'll look for something more challenging now. Will ping you when I need help.

Cheers!

**Comment by siddjai** [comment]
Please assign this to me.

**Comment by Adrianzatreanu** [comment]
ping @siddhanjay

**Comment by sils** [comment]
unassigning due to inactivity

**Comment by siddhanjay** [comment]
@Adrianzatreanu You pinged the wrong person .
