### ISSUE TITLE
Split ConsoleInteraction.py

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#2891]
Maybe we should split it in 2 files depending on methods (for bears/global use).

**Comment by Makman2** [comment]
In this case I need to ask you, do you have something explicit we shall split up? :)

**Comment by sils** [comment]
is there anything for global use in there? :thinking:

**Comment by Nosferatul** [comment]
Well I've been thinking only to move the functions that are for `bears`. As a developer, if you don't know what are you searching for, but it's for a bear, you should only search in a more specific file. The functions are well named also

**Comment by Makman2** [comment]
which ones are for bears? Ideally everything in this file is related to user interaction only^^

**Comment by Nosferatul** [comment]
`show_bear` `show_bears` `print_bears` but maybe I'm wrong 🤔

**Comment by Makman2** [comment]
these are for showing/printing bears on the terminal, this is user interaction specific :)

**Comment by palash25** [comment]
I have a different opinion I think `show_bears` and `print_bears` belong in this file. If anything that needs to be taken out of this file it is the formatting and styling functions `color_letter`, `format_lines` and `highlight_text`. Maybe they can be moved to something like `ConsoleStyling.py` and then that can be imported to `ConsoleInteraction.py` to be used in its functions.

I think this will be a better design since the real "console interaction" begins from the `print_section-beginning` function and the styling functions and constants like `FILE_NAME_COLOR` sitting at the top of the file feel like unnecessary noise.

your thoughts on this @Nosferatul @Makman2 

I would be happy to work on this :smile:

**Comment by Makman2** [comment]
Hmm not sure if it's really worth to fix that now, we don't gain something from that really. @palash25 if you think it's worth to do it, feel free to start. If not, I would actually close thise issue ;)

**Comment by palash25** [comment]
@Makman2 on second thoughts I think this is not really worth the effort. Lets close it.

**Comment by jayvdb** [comment]
We have a PR about color_letter, format_lines and highlight_text.  Finding a new home for them might be helpful.

**Comment by jayvdb** [comment]
Here it is https://github.com/coala/coala/pull/5215

**Comment by jayvdb** [comment]
Also relevant is adding module docstrings to create a sense of purpose for each file: https://github.com/coala/coala/issues/5359

**Comment by Makman2** [comment]
@jayvdb shall we rather add new issues? This one is not well defined now, so I would rather close it.

**Comment by jayvdb** [comment]
I'm not sure we need a new issue even.  The PR will sort itself out.
