### ISSUE TITLE
Bash Autocompletion not working

### ISSUE THREAD

**Issue by nikhaas** [coala/coala#2914]
Bash autocompletion does not work for me. I strictly followed the steps from [coala docs](http://coala.readthedocs.io/en/stable/Users/Tutorials/Shell_Autocompletion.html).

```
pip install argcomplete
echo 'eval "$(register-python-argcomplete `which coala`)" '  >> .bashrc
source .bashrc
```

but it does not work.

I have installed `Python 3.5.1`, `argcomplete 1.6.0`, `cib` (not coala-bears) and the bears `PEP8Bear, RadonBear`.

This is the output of the eval statement:

```
_python_argcomplete() {
    local IFS='
               '
    COMPREPLY=( $(IFS="$IFS"                   COMP_LINE="$COMP_LINE"                   COMP_POINT="$COMP_POINT"                   _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS"                   _ARGCOMPLETE=1                   "$1" 8>&1 9>&2 1>/dev/null 2>/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    fi
}
complete -o nospace -o default -F _python_argcomplete "/home/niklas/anaconda3/bin/coala"

```

Is anyone facing the same issue?

**Comment by jayvdb** [comment]
See https://github.com/coala/documentation/pull/424

**Comment by all3fox** [comment]
@nikhaas thanks for your report, coala documentation was corrected to use just `coala` instead of `which coala` because that was messing up with `argcomplete` scripts.

Updated autocompletion instructions [are here][1], let us know if you are still having problems. Otherwise, we will be closing this issue.

[1]: https://docs.coala.io/en/latest/Users/Shell_Autocompletion.html

**Comment by jack17529** [comment]
@jayvdb I have worked on this type of issue in OWASP ZSC shellcoder should I assign it to myself?

**Comment by all3fox** [comment]
@jack17529 I believe there is no issue here. Please see the doc link that jayvb provided above, and then follow to https://github.com/coala/documentation/issues/388

If you do so, you will notice that this issue and that issue appear to be the same and that that issue was resolved. jayvb and I were just pinging nikhaas (in case he is still interested) to let them know that their issue is probably resolved too and will be closed if nikhaas does not report otherwise here.

**Comment by nikhaas** [comment]
I tested both `zsh` and `bash` and both seem to work fine. Thank you for fixing!
Just a question: I am using `oh-my-zsh`. Is it possible that one does not need then
```
autoload bashcompinit
bashcompinit
```
before the `eval` statement? It seems to work both ways, with and without `bashcompinit`.

**Comment by all3fox** [comment]
Well, the github for `oh-my-zsh` features plugins that seem to enable `bashcompinit`, so I would say yes:

https://github.com/robbyrussell/oh-my-zsh/search?utf8=%E2%9C%93&q=bashcompinit

**Comment by all3fox** [comment]
@jayvdb this is a ping that you could close this issue and the related issue opened by you:

https://github.com/coala/coala/issues/3887

In short: the people who report the issue can now set autocompletion up just fine and your suggestion (the issue I am linking to) of relying on global autocompletion mode of `argcomplete` is, in my opinion, a bad idea because in that case only `bash` shells are supported.

Current coala way of using the local-ish mode of argcomplete (as [described in documentation][1]) works for both `bash` and `zsh` and has been reported to work fine by nikhaas from this issue and by Naereen in https://github.com/coala/documentation/issues/388

[1]: https://docs.coala.io/en/latest/Users/Shell_Autocompletion.html
