### ISSUE TITLE
Newcomer guide should tell people to become "developer"s

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3229]
_From @coala-bot on November 13, 2016 19:57_

See discussion above. difficulty newcomer

Opened via [gitter](https://gitter.im/coala/coala/?at=5828c5a3e462097a304463df) by @sils

_Copied from original issue: coala/documentation#301_

**Comment by Mariatta** [comment]
_From @rahul-kumi on November 18, 2016 17:6_

hey, I would like to work on this issue, can i be assigned to it.

**Comment by Mariatta** [comment]
_From @MihneaVorovenci on November 19, 2016 14:2_

Assign me this issue.

**Comment by Mariatta** [comment]
_From @sils on November 19, 2016 14:16_

this issue is already taken @MihneaVorovenci

**Comment by CosminIcatoiu** [comment]
Is this issue still up?

**Comment by sils** [comment]
@rahul-kumi please confirm if you still intend to work on this

**Comment by CosminIcatoiu** [comment]
@sils . If he is not working, I can be assigned. I did 2 newcomers issues so i can move to low difficulty or i can do this too and then move to low diff. I go to uni now so please assign me if you consider (and if he is not working ofc).

**Comment by sils** [comment]
(start templated message)
Hey,

it seems you're well acquainted with the workflow!

We recommend to not do newcomer issues anymore because they take us more time to file than to fix them - let other newcomers can have a few as well. The next level for you are the [low difficulty issues](http://tinyurl.com/coala-low) - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

Cheers!

**Comment by CatalinFetoiu** [comment]
You can assign me this issue if it's still available :)

**Comment by nemaniarjun** [comment]
We already have that info in the newcomers guide... 

> You will start as a newcomer, which is kind of a trial. If you complete the following tasks, you will become a developer at coala:
>1. run coala on a project of yours
>2. merge a difficulty/newcomer Pull Request
>3. review at least a difficulty/newcomer Pull Request
>4. merge a difficulty/low Pull Request
>5. review at least a difficulty/low or higher Pull Request

**Comment by SanketDG** [comment]
We already have this?

**Comment by meetmangukiya** [comment]
Yes

**Comment by sils** [comment]
indeed
