### ISSUE TITLE
YAPFBear default settings are not identical to upstream YAPF

### ISSUE THREAD

**Issue by rgreinho** [coala/coala#3241]
YAPFBear, ``space_between_ending_comma_and_closing_bracket`` has a default of `false`
(https://github.com/coala/coala-bears/blob/master/bears/python/YapfBear.py#L41), whereas
the upstream YAPF setting has a default of `true`
(https://github.com/google/yapf/blob/556f9155db15db18e972655ec6f79d7f4c9a6c6c/yapf/yapflib/style.py#L194)

**Comment by sils** [comment]
Hm, I wonder why we did that... though we don't necessarily use the tools default: coala tries to help you when it comes to settings, to abstract away the tool that lies below, you'll also not always have the same names. This is so you can use the same setting names consistently across all the bears and don't have to read up on them every time.

When it comes to defaults we usually *do* take the tools default because they likely took more time to set it right.

**Comment by sils** [comment]
So let's just set t to `True` by default. I'm marking this newcomer so this'll probably be done rather quickly by the weekend or so ;) (big hackathon coming up)

**Comment by Makman2** [comment]
I think this should be an issue in `coala-bears`^^

**Comment by sils** [comment]
@rgreinho if you want to rely on the new behaviour, install coala with `pip install coala-bears --pre` to get the version straight from master

**Comment by rgreinho** [comment]
Got it! Thank you for merging the PR.

**Comment by sils** [comment]
thank you! :)
