### ISSUE TITLE
In Writing Documentation section, add link to reST primer

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3521]
One link I found useful when just starting to write documentation is this link:
http://www.sphinx-doc.org/en/latest/rest.html 

It provides basics of restructuredText for those new to it.

I think we should add this into our Dev Guide under Writing Documentation, http://api.coala.io/en/latest/Developers/Writing_Documentation.html

**Comment by CosminIcatoiu** [comment]
Btw isn`t it a newcomer problem more than a low one ? :) ( Just asking )

**Comment by Mariatta** [comment]
If you are interested, I'll remove the newcomer label and assign it to you. :)

**Comment by CosminIcatoiu** [comment]
I can do it. But not necessary because it is for newcomer or low. I was told to move low ones but don`t really do issues just because they are labeled somehow but because i can help. However you believe. If you consider it fits better a newcomer would be better to let it to one because there are not many newcomer issues opened now :) .

**Comment by Mariatta** [comment]
I will mark this low, because it's not a straightforward task of copy pasting the link to the docs, and be done with it, but will require a little knowledge of restructured Text already, and some writing.

**Comment by CosminIcatoiu** [comment]
Ok :) :+1:

**Comment by Mariatta** [comment]
Thanks for taking this on! :)

**Comment by CosminIcatoiu** [comment]
I will do it later tonight . I can`t really do it right now . Sry

**Comment by Mariatta** [comment]
no prob

**Comment by CosminIcatoiu** [comment]
@Mariatta think i did it. Have a look when you have time :)
