### ISSUE TITLE
files setting can not contain non-unicode files

### ISSUE THREAD

**Issue by rhemon** [coala/coala#3529]
```
(venv) MBPs-MacBook-Pro:coala-bears rhemon$ coala -f ./test-img/img.png 
Executing section Default...
[WARNING][18:23:39] Failed to read file '/Users/mbp13inch/Documents/Workspace/coala-bears/test-img/img.png'. It seems to contain non-unicode characters. Leaving it out.
Executing section python...
[WARNING][18:23:40] Failed to read file '/Users/mbp13inch/Documents/Workspace/coala-bears/test-img/img.png'. It seems to contain non-unicode characters. Leaving it out.
Executing section autopep8...
[WARNING][18:23:40] Failed to read file '/Users/mbp13inch/Documents/Workspace/coala-bears/test-img/img.png'. It seems to contain non-unicode characters. Leaving it out.
Executing section linelength...
[WARNING][18:23:43] Failed to read file '/Users/mbp13inch/Documents/Workspace/coala-bears/test-img/img.png'. It seems to contain non-unicode characters. Leaving it out.
Executing section CI...
Executing section commit...
[WARNING][18:23:44] Failed to read file '/Users/mbp13inch/Documents/Workspace/coala-bears/test-img/img.png'. It seems to contain non-unicode characters. Leaving it out.
Executing section rst...
Executing section PythonPackageInit...
[WARNING][18:23:45] Failed to read file '/Users/mbp13inch/Documents/Workspace/coala-bears/test-img/img.png'. It seems to contain non-unicode characters. Leaving it out.
```
Same result if I use jpg files.

**Comment by pratyushprakash** [comment]
We don't have support for image files

**Comment by Makman2** [comment]
We don't have generally support for files that are not utf8-encoded. This is going to come with the `FileProxy` we plan for bears. Currently we use the file-dict, which is loaded before a bear-run, so we can't do anything about it for now.

See https://github.com/coala/coala/issues/3530

**Comment by jayvdb** [comment]
The PEP for FileProxy has the same problem. My PR of that PEP went some way towards removing that limitation.
However all that is orthogonal to this problem.  This is a global external linter bear with no dependencies. There is no reason for coala to be opening these files. Any opening and reading of these files by coala is performance problem, as the external linter will be doing the same.

**Comment by Makman2** [comment]
The PEP is a bit outdated^^

`FileProxy` could easily handle such cases, imo it will fix this kind of problem. Also to not open files if they error out, and placing `{'non-utf8-file': []}` into the file-dict is totally careless, this leads to inconsistent analysis behaviour.

**Comment by jayvdb** [comment]
What about ` {'non-utf8-file': None}` to register there is a file, but it isnt a line based file that the rest of coala knows what to do with?

I was actually thinking of some extra flag on a global bear which informed coala to not process `files` at all, but instead pass it through to the global bear to be interpreted differently (and then we'd use code review to ensure those bears do something sensible with it).  I've no idea how disruptive that would be.  The biggest problem would be if `bears` contained a global bear and a normal bear, but that could be an error condition.

**Comment by Makman2** [comment]
that sounds complicated. Though `{'non-utf8-file': None}` could be used, we need to make users aware of this + they need to make always a fallback then -> `if file is not None: blub`. Having some kind of flag to automatically filter non-utf8 files is bad as it offloads more work for the core to manage files and makes it inconsistent.

> I was actually thinking of some extra flag on a global bear which informed coala to not process files at all, but instead pass it through to the global bear to be interpreted differently

tell me more :D

But about the `FileProxy`: In the first implementation it wouldn't work much differently from the current behaviour, we would just try to load with utf8-encoding. To support binary files we would change the load-behaviour as following:
- Load the raw binary stream into `self._raw` 
- Decode bytes into utf8 and place result into `self._content`, by default it will use universal newlines mode. Not sure yet how to disable universal newlines nicely
-  Split the content and place result into `self._content_splitted`

When decoding into `self._content` fails, we could mark it internally as failed and throw an error when accessing it. But the file proxy would still be available, with the filename and binary content.

As `FileProxy` is a class, we can change behaviour like we want later and maintain compatibility very good.

So far from that plan :)

**Comment by jayvdb** [comment]
This isnt the place to debate the cEP, and especially debate how wonderfully it could do things that are not specified in it.

This is about external linters which are going to load the contents, maybe in a Java or Ruby runtime, and that file could be terabytes. Why do you want the coala python runtime to load a second copy of the file.

This issue is about letting a bear explicitly tell coala to get out of the road. If a bear explicitly says it doesnt want the file contents loaded inside coala, coala should support that, and make the necessary adustments to queuing of processing. Otherwise, bears will have ugly hacks around this, and the usability suffers. Please read rhemon's PR.

**Comment by Makman2** [comment]
Thing is I don't want to invest time into some "workaround" while FileProxy can easily handle this.

> Otherwise, bears will have ugly hacks around this, and the usability suffers.

Don't agree with this, some flag to tell the core to do something means we need to hack around it again. I want to keep the core as simple as possible (the current implementation is already damn unreadable/not-understandable). Also this is quite an API feature we should not implement carelessly because on long term with FileProxy it will be obsolete, and once it's there we need to care about deprecation etc etc. \+ the user needs to tell the bear with a variable to ignore files. With the `FileProxy` you just don't need to do this, just don't access the utf8 decoded content (which is not available for jpg files for example).

If you want this issue solved, I think we should drive the FileProxy to make it right from beginning.
