### ISSUE TITLE
Poor highlighting in case of Mac OSx users. 

### ISSUE THREAD

**Issue by HitRam** [coala/coala#3544]
I used some SpaceConsistencyBear and InvalidLinkBear. In case of MAC OSx, it highlights the inconsistencies with green colour just like a marker does, but it rather makes it difficult to read the inconsistencies.

Here is the link to the screenshot. 
http://i.imgur.com/3RP7cRW.png

**Comment by hemangsk** [comment]
I am able to reproduce this one on Sierra Terminal 


<p align="center">With Basic theme</p>
<img src="https://cloud.githubusercontent.com/assets/13018570/21943315/c144c044-d9f6-11e6-8700-964b7ff6828e.png"/>


<p align="center">Basic theme inverted colors</p>
<img src="https://cloud.githubusercontent.com/assets/13018570/21943317/c2b38988-d9f6-11e6-89b2-5a748c3f09db.png"/>

Since there are almost 10 themes for the default terminal application and user can be using any of these themes, it doesn't seem really easy/feasible to decide on a "universal" color scheme that'd look good on all of the terminal themes, some possible solutions

-  We can give options to select color schemes in coala, that'll require some design, 
In ConsoleInteraction.py [L 75-80](https://github.com/coala/coala/blob/master/coalib/output/ConsoleInteraction.py#L76)

- Try to modify the current color scheme, taking in account the Linux, windows, and  osx's default terminal scheme.

- ```--no-color``` Option gives a cool output on osx, so we can mention in the documentation about using ```no-color``` in case of os x color trouble, I doubt this as a solution though because users who don't like terminal colors would already be using --no-color.
![screen shot 2017-01-14 at 1 28 14 am](https://cloud.githubusercontent.com/assets/13018570/21944114/68c0b1e0-d9fa-11e6-8dd1-a199dbf31de1.png)

these are just a few crude ideas to solve this one, what do you think ?

**Comment by Makman2** [comment]
though this weird highlighting of yours looks like a bug^^ you should open another issue for the strange two-lines-spanning highlight^^

**Comment by ashwini0529** [comment]
We can show up a notification that please use `--no-color` in case of Mac OS.

**Comment by Makman2** [comment]
we should just use better colors by default I think, unless someone changes the default colors for terminal. Then he/she is responsible herself^^

**Comment by ashwini0529** [comment]
Should I give it a try then?

**Comment by Makman2** [comment]
sure :D

**Comment by HitRam** [comment]
@hemangsk  Yeah, I think using better colours by default is a good idea.

**Comment by HitRam** [comment]
@Makman2 The strange two line spanning thing didn't appear in @hemangsk 's MAC. So should I create another issue?

**Comment by hemangsk** [comment]
I typed the same code in vim and ST2
```
def do_something():
   print(a+b)
```
vim adds a new line character by default.
When I wrote that in ST2, line spanning bug came,
![screen shot 2017-01-15 at 5 53 28 pm](https://cloud.githubusercontent.com/assets/13018570/21962441/1c5fd170-db4c-11e6-87f2-9fe36cc0eb4b.png)

**Comment by Makman2** [comment]
@HitRam yes please

**Comment by ashwini0529** [comment]
Where are the color codes used? For highlighting?

**Comment by Makman2** [comment]
looks like

**Comment by sils** [comment]
We have the same issue on windows including some beeping with @seblat because apparently some of the characters are interpreted y the powershell as beeps. This is really important to get fixed for our windows users.

@HitRam any progress?

**Comment by HitRam** [comment]
@jayvdb  This was taken by @ashwini0529 . But I tried finding the bug. Couldn't get much but found that this happens only when there is some special character in the code like 

```
def something():
    a  .
```

```
def something()
    a 7
```

Although not all special characters would lead to this kind of spanning. 
One more thing I noted was that in linux actually other lines are getting highlighted and not the ones which are getting on mac or windows.

**Comment by sils** [comment]
yeah so we replace spaces by this unicode dot to make them visible, I think
that is partly the reason why things go haywire, also the arrow thing we
use to visualize tabs

**Comment by Makman2** [comment]
weird anyway, as I tested those dots on Windows and they seem to work fine (so far :3)

**Comment by HitRam** [comment]
@sils By commenting https://github.com/coala/coala/blob/master/coalib/output/ConsoleInteraction.py#L191-L193 these lines, it didn't convert space into unicode dot but still the problem remains, it was still highlighted the same way! 
<img width="623" alt="screen shot 2017-02-06 at 6 12 46 pm" src="https://cloud.githubusercontent.com/assets/19632768/22647510/e7f56a82-ec97-11e6-80b5-6e81e9d229b1.png">

**Comment by sils** [comment]
So maybe it is pygments?

On Feb 6, 2017 1:43 PM, "Hitesh Ramchandani" <notifications@github.com>
wrote:

@sils <https://github.com/sils> By commenting https://github.com/coala/
coala/blob/master/coalib/output/ConsoleInteraction.py#L191-L193 these
lines, it didn't convert space into unicode dot but still the problem
remains, it was still highlighted the same way!
[image: screen shot 2017-02-06 at 6 12 46 pm]
<https://cloud.githubusercontent.com/assets/19632768/22647510/e7f56a82-ec97-11e6-80b5-6e81e9d229b1.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/coala/coala/issues/3544#issuecomment-277669949>, or mute
the thread

**Comment by ashwini0529** [comment]
I want to work on some other issue. Please unassign me this issue.

**Comment by sils** [comment]
you can use `cobot unassign` now

**Comment by ashwini0529** [comment]
cobot unassign

**Comment by ashwini0529** [comment]
We can make a config file where all the colors related to Console Interaction can be listed.
It would be very easy then to fix such issues.

**Comment by Makman2** [comment]
Problem is that even with right colors, the piece of text that is highlighted is wrong^^ + we want to avoid doing stuff from pygments on our own. Don't reinvent the wheel ;)

**Comment by ashwini0529** [comment]
What should be the possible solution then? 
I've been thinking from quite a long time but couldn't come up with an idea.
All themes need different highlighting colors which is like not an easy task.

**Comment by Makman2** [comment]
ah okay you mean the different color schemes. Yes that would be okay, but this issue is not about color schemes but to fix this wrong highlighting^^

**Comment by yukiisbored** [comment]
Hello, I can confirm the cause of this is because of terminal emulators that continues the ANSI color escape code.

These are the emulators I've tested so far: 
Affected: Any vte-based terminal emulators, macOS terminal emulator.
Not affected: st, termite, rxvt-unicode, xterm

**Comment by Makman2** [comment]
So we should maybe file an upstream bug at pygments to handle that correctly for different terminals?

**Comment by yukiisbored** [comment]
@Makman2 I don't know if this a problem with pygments or not. Since I think the highlighting is not caused by it? Not sure.

**Comment by Makman2** [comment]
Created https://bitbucket.org/birkenfeld/pygments-main/issues/1371/colors-span-multiple-lines-if-color-is-not to discuss this also on pygments :)

**Comment by sangamcse** [comment]
<img width="862" alt="screen shot 2018-03-16 at 12 54 00 am" src="https://user-images.githubusercontent.com/26381717/37486773-7e8a9940-28b5-11e8-952a-fa909d64b601.png">
<img width="572" alt="screen shot 2018-03-16 at 1 00 25 am" src="https://user-images.githubusercontent.com/26381717/37486776-7f2c532a-28b5-11e8-9d36-00425c7b41c3.png">
I used these 2 terminal on High Sierra but there is no highlighting where I used https://github.com/coala/coala/issues/3544#issuecomment-272692099 to reproduce the problem.
Also, I tried https://github.com/coala/coala/issues/3544#issuecomment-272537357 and got 
<img width="574" alt="screen shot 2018-03-16 at 1 06 45 am" src="https://user-images.githubusercontent.com/26381717/37487107-871364e2-28b6-11e8-807c-4411043d15df.png">

**Comment by Makman2** [comment]
So everything is working again @sangamcse ?

**Comment by sangamcse** [comment]
On my system i.e, OSx 10.13.4 High Sierra, yes it is working as it should. As you can see the screenshots.

**Comment by Makman2** [comment]
If someone has still problems on latest macOS, please comment :smile:
