### ISSUE TITLE
docs: Use python3 and pip3 everywhere

### ISSUE THREAD

**Issue by jack17529** [coala/coala#3921]
It should be mentioned how to deal if user has both python 2 and python 3 installed in system (ubuntu)

**Comment by jayvdb** [comment]
Use `python3` everywhere in docs instead of `python`?

**Comment by jack17529** [comment]
@jayvdb yes something needs to be mentioned ,well I am working on this.

**Comment by Madhukar-SH** [comment]
If the issue is referring to http://docs.coala.io/en/latest/Users/Install.html , 
There is just one thing to fix that is
'$ pip show pip' should be changed to '$ pip3 show pip'

Beacue 'pip show pip' would lead to installation of python-2.7 pip if it wasn't installed. 
But the requirement is pip3 which is python3-pip :)

**Comment by jack17529** [comment]
@NiklasMM here it is and I thought nothing happend and my internet too blew up,sorry.

The only problem is that in commit message there is a typo gitignore-->Development_Setup.rst

**Comment by jack17529** [comment]
@NiklasMM please comment if you have seen it and want me to correct anything

**Comment by NiklasMM** [comment]
@jack17529 it seems like you're commenting on the Pull Request #3922, but this is the related issue. Please keep any comments regarding a pull request to the discussion there.
