### ISSUE TITLE
Create a new initiatives/gsoc label

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3944]
Creating a new initiatives/gsoc label would prevent it from being assigned to people who are not aware of the projects shortlisted for gsoc. Can be assigned to a person with write access. :)

**Comment by jayvdb** [comment]
Could be useful, but it needs to be created in all relevant repos ; see roadmap.
Main problem with labels is only maintainers can add them on github, unless we get bot support.
Can we solve that somehow? @zulipbot is an easy quick fix.

But really, if it is part of your project, shouldnt it be assigned to you early? 

(In addition,) We should create a shortcut http://coala.io/gsoc17review which uses 10 `author:x` to should relevant patches which need quich reviews. (And other shortcuts? )

**Comment by Makman2** [comment]
Yeah rather assign those issues to yourself early. I think it's fine in line with gsoc^^

I think it would be more useful for reviewing PRs, so people from other projects are encouraged to review each other and give further ideas.

**Comment by jayvdb** [comment]
So this didnt happen, and some alternatives were improvised like using "gsoc: " in issue and pr titles.

A very quick assessment : there was very little chance that non-gsoc people helped the gsoc projects.  Maybe a few beginner tasks were done, but mostly the gsoc projects should not be including tasks that other people *might* do. So as Makman2 suggests, pre-assigning critical path tasks to the gsoc participant is the easiest approach.

Another idea is to have a GCI and GSOC overlay for avatars of people participating in GCI & GSOC, so it is easier to spot them, and then make sure their profile url goes to their website with the blog, so that their gsoc project is discover-able by someone curious by the GCI/GSOC overlay on their avatar.
https://github.com/coala/projects/issues/370

I think we'll have lots of better mechanisms by next GSOC, and should re-evaluate how to optimise the next GSOC closer to the time it starts.

Anyway, this is an org level issue, so it should be continued in https://github.com/coala/meta .
