### ISSUE TITLE
Asserion error in Tests and Travis

### ISSUE THREAD

**Issue by madhukar01** [coala/coala#3955]
Errors are occuring due to http://httpbin.org/status/418 returning `500 Internal server error` instead of `418 client error`.

Due to this Travis builds, local py.test and appveryor builds are failing.
None of the PR made now are going to pass the tests.
 
` AssertionError: "418 Client Error" does not match "500 Server Error: INTERNAL SERVER ERROR for url: http://httpbin.org/status/418"
tests/bears/BearTest.py:328: AssertionError
`

**Comment by all3fox** [comment]
The address you mention is working fine now:

```
alex@tardis ~/Code/coala (git)-[master] % wget httpbin.org/status/418                                                            :(
--2017-03-22 13:23:23--  http://httpbin.org/status/418
Resolving httpbin.org... 54.235.135.158, 54.225.186.255, 54.243.85.55, ...
Connecting to httpbin.org|54.235.135.158|:80... connected.
HTTP request sent, awaiting response... 418 I'M A TEAPOT
2017-03-22 13:23:23 ERROR 418: I'M A TEAPOT.
```

Please close issue or explain in more detail what you mean by:
> Due to this Travis builds, local py.test and appveryor builds are failing.

**Comment by jayvdb** [comment]
This was a transient problem in the httpbin.org service.

We could prevent these network errors by using [pytest-httpbin](https://pypi.python.org/pypi/pytest-httpbin) to run a local instance of the same web service, but that is probably overkill since we only have two tests which use httpbin.org , and I doubt pytest-httpbin knows when to start and stop the local httpbin service to avoid wasting resources.
