### ISSUE TITLE
Linter tutorials brush-up

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4120]
The current guides (`Writing_Linter_Bears.rst` and `Linter_Bears_Advanced.rst`) are a bit out-of-date. New features need to be added, any we should maybe provide a few more examples.

Things that are currently in my mind:
- Better global-bear documentation
- New features not mentioned inside the guide (new unified-diff output format, global-bear, `process_diff` function)

This issue requires knowledge about `@linter` and many of its functionalities. So take this as a chance to learn more about `@linter` if you haven't yet ;)

For questions regarding specific `@linter` topics, ping me :+1:

**Comment by RaiVaibhav** [comment]
Please Add label `initiative/gci` :)

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by kriti21** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by Makman2** [comment]
@kriti21 as this seems to be your first issue, are you sure you want to start with a `difficulty/low` one, especially one that requires specific knowledge of the addressed component?

**Comment by kriti21** [comment]
Most of the difficulty/newcomer issues are labeled under GCI/initiatives as well. I am a college student so can't possibly take any of those. I am up for any beginner friendly issue that would help me get started contributing to coala. Any guidance would be helpful @Makman2

**Comment by RaiVaibhav** [comment]
@kriti21  start with `newcomer task` :wink: , IMO it a steps which everyone needs to follow and it is necessary.

**Comment by manankalra** [comment]
@Makman2 I can take this as I've worked on global bears before and had to go through a lot of source-code to figure things out. ;)

**Comment by manankalra** [comment]
>If your underlying tool generates a corrected file or a unified-diff of the corrections, the class automatically generates patches for the changes made and yields results accordingly.

This is mentioned in the docs in relation to the `unified-diff` output format. That is, the developer needs to take no additional care of it. So, what else needs to be added in this case? An example stating what a unified-diff actually means here and a short summary of how we are handling it?

**Comment by Makman2** [comment]
Hm I think that's already enough. But if you think there's more to be described feel free to add stuff.

**Comment by Makman2** [comment]
But the `process_unified_diff` function is not mentioned I believe.

**Comment by manankalra** [comment]
@Makman2 
I have a few questions:
- A user will need to override `process_output` if the output of the linter being used isn't one of {`regex`, `corrected`, or `unified-diff`}, right? For example: in case of JSON output. So, when will the need of overriding {`process_output_regex`, `process_output_corrected` or `process_output_unified_diff` will arise?
What I understood is - providing `output_format=regex` and `output_regex=r'some_regex'` under `@linter` does the same job as overriding `process_output` and then using `self.process_output_regex(...)` inside it. (Similarly, for the other two as well.)

- `process_diff` is needed just because of the variations that exist in diff formats? And `process_output_unified_diff` deals with one of those variations (i.e. of the unified format)?

- The linters that produce output in a diff format are also capable of applying patches, right? Therefore, `process_diff` does the same thing as what providing a corrected file does i.e. shows what's bad and a correction for it. The only difference is that the output formats are different.

**Comment by jayvdb** [comment]
Looking quite good so far.
