### ISSUE TITLE
Development_Setup.rst: Unused target "dev-notes"

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4222]
Development_Setup.rst starts with

```
.. _dev-notes:
```

This is unused and should be removed.

**Comment by mridubhatnagar** [comment]
@jayvdb RSTcheckBear is not yet a part of .coafile. So whoever would work on this first will need to make changes in the .coafile.
Adding rstcheckbear in .coafile would raise bunch of other changes that I have already fixed in
#4211.

Because of this reason I have fixed this issue in #4211 itself.
We can close this as well. Once #4211 gets merged.

**Comment by jayvdb** [comment]
@mridubhatnagar , no, someone can fix this bug without enabling RSTcheckBear.

This bug should be fixed before #4211.

**Comment by nityeshaga** [comment]
Just to be clear, all that is needed to resolve this issue is removing the line

> .. _dev-notes:

from the Development_Setup.rst file. Am I correct?

**Comment by sims1253** [comment]
@Balaji2198 please make sure to assign the issues you are working on so that others don't waste their time doing the same work you are doing.

**Comment by jayvdb** [comment]
Unassigned due to inactivity.  @Balaji2198, please ask on Gitter if you want to resume this work.
Any other newcomers want to grab this one?
