### ISSUE TITLE
coala should recheck the issue it pointed while running locally

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4443]
coala should recheck the issue it raised after user has fixed it, it currently skips the line on which the issue was raised and also the newly added lines.
type/bug difficulty/hard
Opened via [gitter](https://gitter.im/coala/coala?at=595ba775f5b3458e3010233f) by @Monal5031

**Comment by Makman2** [comment]
Could you be a bit more specific? I can hardly understand the issue ;)

(btw: bug issues are usually `difficulty/medium` :) )

**Comment by Monal5031** [comment]
While using coala locally, an issue was pointed out, which I tried solving and I had to add new lines just under the line coala pointed (the newline I added also had an issue), and after making the changes coala skipped that line.
Also, when I tested a little more, I found out that coala never checks if the issue it pointed out was corrected or not (we have to rerun coala to be sure).

**Comment by Makman2** [comment]
yeah coala loads the files into RAM and operates on those instead of the files directly. This is a) faster b) safer when outside modifications occur. We have this issue to consider some different behaviour in that direction: https://github.com/coala/coala/issues/3912

I wouldn't consider this a bug as this is currently intended. If you agree I would close this issue and redirect the discussion again on https://github.com/coala/coala/issues/3912 :)

**Comment by Monal5031** [comment]
Okay sure @Makman2 please close this one.
