### ISSUE TITLE
FilterHelper.get_all_filters_str(): Shall it be kept or inlined?

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4496]
Imo this is application specific code displaying text to the user, that's why I vote for inlining it into the currently single occurrence in code.

@shreyans800755 what do you think? I know we already discussed that, though I want some third party opinions on this^^

**Comment by shreyans800755** [comment]
IMO, it is okay to inline it at the moment. But I'm afraid, what if its usage becomes high in future ? In that case, every time, that small snippet will have to be rewritten. But again, the concern is, hardly anybody will know about this function. And experienced python programmers will always tend to write a single line of code instead of finding if there's already a function for that.
So, I guess inlining is better.

**Comment by shreyans800755** [comment]
>  want some third party opinions on this^^

+1

**Comment by Makman2** [comment]
Okay let's just do it if nothing has something against it ;)
