### ISSUE TITLE
remove test requirement on urllib3 which is controlled by requests requirements

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4512]
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=5972b34d614889d475db0099)

**Comment by jayvdb** [comment]
https://github.com/coala/coala/pull/4294 introduces a direct dependency version requirement on urllib3, but that is an indirect dependency about whose version we can not control.

urllib3 released a new version, which requests doesnt accept.

The result is the docker is broken, and other things will also break.

**Comment by jayvdb** [comment]
The problem was reported by @yash-nisar at https://gitter.im/coala/coala?at=5972195b1c8697534a4851e7 , seen at
https://travis-ci.org/yash-nisar/docker-coala-base/builds/256085447

**Comment by jayvdb** [comment]
Now regarding solution, we need to backtrack a bit.

https://github.com/coala/coala/pull/4294 was solving https://github.com/coala/coala/issues/4293 , which was a transient problem during the "requests is broken" phase which was mostly tracked at https://github.com/coala/coala/issues/4277 .

requests 2.14.2 was the sane version before that mess.

During that mess, the main breakage in coala was https://github.com/coala/coala/issues/4282.  https://github.com/coala/coala/pull/4283/commits/6785f4aff68503e1ccbb16420fe614a23e78f6f9 was merged to solve that, adding the newly found exception that was being raised:
```
requests 1.15-1.16.3 caused one test to raise a different exception than previously expected.
```

The addition of urllib3 as a dependency was trying to solve the fact that urllib3's `ProtocolError` was a moving target as requests screwed around with their packaging/vendoring system.

A more stable solution is using `requests.model.ProtocolError`, as this exception has existed at that name since requests 2.4.0 (https://github.com/requests/requests/commit/47d0517d6), and we only depend on 2.12+.

**Comment by jayvdb** [comment]
I can also remove the `ProtocolError` now (https://github.com/jayvdb/coala/commit/0c5ec253bedc) and the test passes : https://travis-ci.org/jayvdb/coala/jobs/256297663

So I suspect that whatever was causing the problem that 6785f4a solved is no longer present.
