### ISSUE TITLE
Add CLI to print only selected bears given in args

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4651]
Opened by @shreyans800755 at [gitter/coala/coala](https://gitter.im/coala/coala?at=5998c94ca7b406262da83962)

**Comment by shreyans800755** [comment]
CC @Makman2 @meetmangukiya

**Comment by mikanaji** [comment]
Can i get this issue?

**Comment by Makman2** [comment]
The issue is currently assigned, please pick another one :)
It's also not labeled right now.

**Comment by shreyans800755** [comment]
@mikanaji I'm waiting for https://github.com/coala/coala/pull/4726 to be completed first. Technically, this issue doesn't require that PR to be merged. But, its good to have. Otherwise, I'll have to resolve a lot of conflicts unnecessarily. Once that PR is merged, which should be done pretty soon, I'll push my changes to this PR.

**Comment by mikanaji** [comment]
@shreyans800755, Thanks!

**Comment by shreyans800755** [comment]
@mykromo Please go ahead with some issue you may find interesting.

**Comment by mykromo** [comment]
Alright. Thanks!

**Comment by shreyans800755** [comment]
@mykromo I've created a PR. Feel free to review.
