### ISSUE TITLE
Three undefined names can raise NameError at runtime

### ISSUE THREAD

**Issue by cclauss** [coala/coala#4700]
flake8 testing of https://github.com/coala/coala on Python 3.6.2

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tests/coalaTest.py:139:30: F821 undefined name 'cm'
            self.assertEqual(cm.error_code, 4)
                             ^

./tests/coalaTest.py:145:30: F821 undefined name 'cm'
            self.assertEqual(cm.error_code, 4)
                             ^

./tests/bearlib/aspects/DecoratorsTest.py:17:16: F821 undefined name 'BEAR_KIND'
        return BEAR_KIND.LOCAL
               ^
```

**Comment by Makman2** [comment]
Nice, thanks for running that on our codebase. I can confirm those being actual problems:
- Undefined name `cm`: The test should declare `cm` via the `with` statement. This raises error currently, because as soon as the exception is raised, the `with`-block is exited. In fact the test is bad and tests nothing.
- Undefined name `BEAR_KIND`: Import is missing. However, it seems `kind()` is never used on the object under test^^ CC @adhikasp

**Comment by Makman2** [comment]
I've split up the issue into smaller ones:
- https://github.com/coala/coala/issues/4701
- https://github.com/coala/coala/issues/4702
