### ISSUE TITLE
travis-ci installing incorrect version of setuptools

### ISSUE THREAD

**Issue by stellargo** [coala/coala#4708]
The following error in travis-ci has been spotted in two recent pull requests https://github.com/coala/coala/pull/4650 and https://github.com/coala/coala/pull/4646 where even after specifying that setuptools 17 has to be installed, it goes on to install setuptools-35.0.2.
I tried this on my local environment which did not give any issue. 
```
2.08s$ pip install pip==9 setuptools==17
Collecting pip==9
  Using cached pip-9.0.0-py2.py3-none-any.whl
Collecting setuptools==17
  Using cached setuptools-17.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Found existing installation: setuptools 36.3.0
    Uninstalling setuptools-36.3.0:
      Successfully uninstalled setuptools-36.3.0
Successfully installed pip-9.0.0 setuptools-35.0.2
0.45s$ python .misc/check_setuptools.py
Checking setuptools==17.0
Failed! pip list reports wrong setuptools:
```

**Comment by gabru-md** [comment]
It happens because of the python environment using different paths.

```sh
$ which pip
$ sudo which pip
```
will give you two different environment paths.

**Comment by atultherajput** [comment]
I am getting same error for this PR https://github.com/coala/coala/pull/4709

**Comment by jayvdb** [comment]
https://github.com/coala/coala/blob/master/.travis.yml#L1 - travis is not using sudo.
The problem is somewhere else.

**Comment by shreyans800755** [comment]
@jayvdb I had this issue in a PR. https://github.com/coala/coala/pull/4726/commits/8f747b3ccb6c8acf201a1cc21ffb541c5190c5d0 commit resolved it. However, `-v -v -v` might not be required.
After some digging, I figured out that, python 2.7 and 3.5 are installed by default. In rest of the versions, `setuptools` was installed multiple time (36.3.0 and 36.0.1 as far as I can remember). But while installing version 17.0, it was uninstalling only one of the versions. So, there was already another version available, due to which version 17 was not being installed.
I still couldn't figure out the root cause. But this commit solves the issue at least in my case.
