### ISSUE TITLE
corobo Usage Stats

### ISSUE THREAD

**Issue by prnvdixit** [coala/coala#4784]
Identify the most regularly used corobo commands.
This task involves three parts:
 - Designing the database to store (command, frequency) pairs
 - Updating the table on each command (or buffer commands, if you're worried about performance)
 - An interface to view the results

Contributors most likely to help regarding issue : @meetmangukiya

label : initiatives/gci

**Comment by Makman2** [comment]
There are probably frameworks for this kind of usage-statistics.
> Designing the database to store (command, frequency) pairs

To calculate usage-frequency it's probably best to store timestamps when a command was invoked, otherwise we are too inflexible (e.g. if we want to display frequency for different months vs years, we need the exact usage distribution)

Shouldn't this issue be btw inside the `corobo` repo?

**Comment by prnvdixit** [comment]
@Makman2 Actually, it was a task listed by @adtac (CC) 😅 - He can explain it better. I found that this had no issue filed - that's why I created one 😉
I accidentally created the issue in this repo (out of flow actually 😛)

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/corobo/issues/311
