### ISSUE TITLE
InvalidFilterException should change name and base class

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4848]
Currently, `coalib.parsing.InvalidFilterException.InvalidFilterException` is based on `Exception`. It should be based on `LookupError`. Also, the `Exception` suffix is untypical. Better `InvalidFilterError` or just `FilterError`

This is also related to https://github.com/coala/coala/issues/4495 and #4821 

cc @aashutoshrathi @shreyans800755

**Comment by mohit2872** [comment]
can you assign this issue to me?

**Comment by barkinunal** [comment]
I will be working on this issue.

**Comment by Makman2** [comment]
This issue should be split up into two smaller ones.

**Comment by Makman2** [comment]
- https://github.com/coala/coala/issues/4872
- https://github.com/coala/coala/issues/4873

**Comment by Makman2** [comment]
@mohit2872 please assign to one of these issue, the other one can be left for other newcomers :)

**Comment by mohit2872** [comment]
I made the required change.

**Comment by jayvdb** [comment]
Ugh, I dont think this problem should be split into two.  The name and the class hierachy of an exception are very closely tied together.

If this is a `LookupError` subclass, the name should indicate that.  Changing it to `FilterError` in one commit, can *not* be followed by simple changing the superclass to `LookupError`, because it would need to change name *again* to `FilterLookupError` or `UnknownFilterError` or something similar.  The name `FilterError` only indicates that it is an exception related to `Filter`, of *any* kind of exception and should only ever be a subclass of `Exception` or `BaseException`.

**Comment by userzimmermann** [comment]
@jayvdb `builtins.AttributeError` and `KeyError` are also based on `LookupError` without mentioning `Lookup` in their name. That's just the Python way. Just like an attribute or key was not found, in this case a filter was not found. Or, more precisely, a bear filter. So IMO, it would just follow the hierarchy and style of default Python exceptions. Prefixing with `Unknown` or `Invalid` is IMO redundant, just like mentioned in https://github.com/coala/coala/issues/4872#issuecomment-344937786

cc @Makman2 @mohit2872

**Comment by userzimmermann** [comment]
@jayvdb But regarding the split I think the same: Should have been solved in a single issue/PR. It's taking up more time this way. But what's done is done ;) And so let's hope that we quickly get that stuff through now! :)

cc @Makman2 @mohit2872

**Comment by Makman2** [comment]
> That's just the Python way.

That's why I think it's legit to split into two, imo semantically two different changes (although related).

**Comment by Makman2** [comment]
> It's taking up more time this way.

It's not critical and we need newcomer issues ;)

**Comment by jayvdb** [comment]
@userzimmermann ,  `AttributeError` and `KeyError` are errors with the *operands* .  `FilterError` is (in this case) an error about the class -- it does not describe what part of the operation parameters was problematic -- and is usually the naming system given to exceptions higher in the tree where there is some need to group a bunch of otherwise unrelated exceptions -- it is ideally not the type of name given to leaf exceptions.  `FilterError` as a leaf exception being raised means there was a problem with a filtering operation, which is not what is happening here when the filter is not able to even be loaded.

**Comment by userzimmermann** [comment]
@jayvdb `FilterError` in this case just means that a filter was not found. That the lookup of the filter in `avialable_filters` failed. That the given filter name was not found as key in that `dict`. That's all

But yes! `FilterError` might sound to blurry. Might feel like there was some problem with a filtering operation as you wrote... So let's find a better name! What about `FilterNameError` :)

**Comment by jayvdb** [comment]
Oh my goodness.  `FilterNameError` means there was a problem with the name given to a filter.

**Comment by userzimmermann** [comment]
@jayvdb Like `NameError` means there was a problem with the name given to a variable? ;)

**Comment by Makman2** [comment]
Tbh there are many philosophies on naming, especially on exceptions. I don't have a problem with any of them, any has a right to exist. I would only pledge for `FilterError` because it's shorter.

> FilterNameError means there was a problem with the name given to a filter, e.g. a filter being created on the fly

Like @userzimmermann said, I don't see it like this either ^^

**Comment by userzimmermann** [comment]
@Makman2 @jayvdb @shreyans800755 @mohit2872 We finally heed some decision here to get https://github.com/coala/coala/pull/4875 done... :)

I recently saw that Python 3.6 introduced a new `ImportError`-derived `ModuleNotFoundError`

So IMO `FilterNotFoundError` would be Pythonic and pretty much self-explanatory without misunderstandings... don't you think?

**Comment by Makman2** [comment]
kk, I'm fine with either way :)

**Comment by Makman2** [comment]
So let's do `FilterNotFoundError`

**Comment by shreyans800755** [comment]
@userzimmermann Looks good to me. Let's go with that name. The issue has been hanging around for quite some time now.
