### ISSUE TITLE
Have de-ansi-ifying flag on the Linter in the core so as to support colorised output.

### ISSUE THREAD

**Issue by aashraybhandar1** [coala/coala#5281]
Some tools produce colorised output, instead of individually writing custom logic to deal with it having a mechanism that supports many colorised output.

**Comment by Makman2** [comment]
Yeah that's actually a cool idea.

It's rather advised to try to disable colored output from the used tool though, but in case the tool can't do that this is a nice feature.

I'm also not sure if this is platform dependent. Could be quite tricky... @aashraybhandar1 you already have an idea for that?

**Comment by Makman2** [comment]
Okay maybe not that tricky, @jayvdb mentioned there are libraries for this.

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/pull/2162/files#r178936744 suggested https://pypi.python.org/pypi/ansicolors which has `strip_escapes`.

This worries me a little, because https://github.com/jonathaneunice/colors/ is a fork of https://github.com/verigak/colors , and neither are very active.

I havent found a better Python library yet, but there are [good ones in other languages](https://github.com/search?utf8=%E2%9C%93&q=strip+ansi+escape&type=Repositories)

I found one possibly useful library, but it would depend on https://github.com/dbcli/cli_helpers/issues/41 being completed.

**Comment by aashraybhandar1** [comment]
I would like to do this issue .. Will do it as soon as it is merged

**Comment by jayvdb** [comment]
Help them do a release by fixing any open issues in their repo

**Comment by jayvdb** [comment]
They did a release of 1.0.2
