### ISSUE TITLE
Add language definition for Haskell

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5330]
https://github.com/coala/coala/tree/master/coalib/bearlib/languages/definitions has no Haskell.
:-(

**Comment by li-boxuan** [comment]
@jayvdb I'm willing to solve this.

**Comment by juliandorville** [comment]
Hi,
I've been looking into contributing to Coala and reviewed the newcomers' guide (so I know to target issues labeled with a newcomer difficulty), and was wondering why this issue was labeled as medium. I think it seems like a pretty simple fix that I could handle, but maybe I'm missing something?
Thanks!

**Comment by jayvdb** [comment]
@juliandorville , a language definition can range from a very basic couple of lines, to being quite detailed like the Python one.

And tests will be required, and those tests would be beyond the typical newcomer.

https://github.com/coala/coala/pull/5428 is a recent example of a language definition modification.

Anyway, an invite to coala org has been sent to you.  Once you accept that, we can assign this issue, and we go from there.  The fact that you are finding a Haskell issue and want to solve it suggests that our newcomer process is not ideal for you.

**Comment by shashwatmishra76** [comment]
@jayvdb I want to try my hands with this one.I guess this issue requires me to add tests for Haskell.Can I be assigned to this?

**Comment by jayvdb** [comment]
Yes some tests would be good.  I've assigned it to you @rishabhgarg25699
