### ISSUE TITLE
doctest polluting tests with TrumpScript alias ts 

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5541]
Similar to https://github.com/coala/coala/issues/5518 , TrumpScript's alias 'ts' is causing problems with https://github.com/coala/coala/pull/5540

**Comment by jayvdb** [comment]
We should also see if this problem is fixed in a more recent version of pytest.  (The incompatible pytest plugins will need to be disabled to test using the latest version of pytest)

**Comment by jayvdb** [comment]
This is blocking a newcomer, so fairly important.

**Comment by jayvdb** [comment]
Still a problem with current release of  pytest 3.6.1

https://travis-ci.org/jayvdb/coala/jobs/393916581#L647

https://travis-ci.org/jayvdb/coala/jobs/393916581#L849

**Comment by pareksha** [comment]
Ah, I see, `Trumpscript` and `TypeScript` have the same alias `'ts,'`, that is why they both are colliding. Even `Language['ts']` in the doctests gives `TypeScript` as output instead of `TrumpScript`.

Changing the alias name of `TrumpSript` will do. But I am looking for a better potential solution.

**Comment by jayvdb** [comment]
Probably best to give it a different alias, which isnt likely to ever be a real alias.

Then we need a new issue about duplicated aliases. The error & docs should explain an alias must be unique.

They also cant be modified, because they can only be allocated once. Any removal of an alias is a breakage.
