### ISSUE TITLE
windows-CI: install packages for skipped tests

### ISSUE THREAD

**Issue by Makman2** [coala/coala#562]
Some tests are skipped on the appveyor build, but to ensure complete support we need all.

**Comment by Makman2** [comment]
Tests that are skipped:
- `ClangASTPrintBearTest`
- `ClangCountingConditionsTest`
- `ClangCountVectorCreatorTest`
- `i18nTest`
- `EspeakPrinterTest`
- `DocumentationCommentTest`

Required packages would be:
- *munkres*
- *libclang*
- *msgfmt*
- *eSpeak*

**Comment by sils1297** [comment]
msgfmt is provided by gettext.

2015-05-20 21:54 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Also
 - `DbusAppTest`
 - `DbusDocumentTest`
 - `DbusServerTest`
 - `DbusTest`
 - `DecoratorsTest`

Which need:
 - python-dbus
 - python-gi

**Comment by AbdealiJK** [comment]
So, I got a win x64 temporarily and tested ClangSharp. It seems like the clang tests always time out.

Not sure why thought ... maybe ClandSharp's lib itself is corrupt ... (?)

**Comment by AbdealiJK** [comment]
To summarize stuff that I was able to install ...

 - [ ] - dbus (Done, but useless without python-dbus)
```
curl -LO https://code.google.com/p/dbus-windows-installer/downloads/detail?name=DBus-Windows-Installer-1.4.1-2.exe&can=2&q=
DBus-Windows-Installer-1.4.1-2.exe /S
```

 - [ ] - python-dbus (needs to be able to run `make` and `configure`)

 - [ ] - python-gi (needs `make` and `configure`)

 - [ ] - clang - The below works for x86 but hangs for x64

 - [ ] - espeak
```
curl -LO http://sourceforge.net/projects/espeak/files/espeak/espeak-1.48/setup_espeak-1.48.04.exe
setup_espeak-1.48.04.exe /NORESTART /SUPPRESSMSGBOXES /VERYSILENT
SET PATH=%PATH%;C:\Program Files (x86)\eSpeak\command_line
```

 - [x] - munkres
```
pip install munkres3
```

 - [x] - msgfmt
```
nuget install Gettext.Tools -Version 0.19.4
SET PATH=%PATH%;%cd%\\Gettext.Tools.0.19.4\\tools
```

**Comment by AbdealiJK** [comment]
Regarding clang on x64 - I manually installed the exe given on the website for winodws (and found some 3rd party ones ...) It hangs on the same line for all of them.

So, somethings wrong on our side - not on clang

**Comment by sils1297** [comment]
@Makman2 please reschedule this as it fits your schedule, I guess we just won't have full windows support for 0.3 then.

**Comment by AbdealiJK** [comment]
I notice a lot of things have been done to cut out unnecessary things (like translations). Is supporting windows still a priority ?

**Comment by sils1297** [comment]
@AbdealiJK as long as @Makman2 supports us on windows support will stay, in general it's a good thing because lots of companies are using windows even for software development, being able to use coala there is in principle a good thing. However I won't push a lot of time into this and we probably won't reach full continuous integration, only for the core modules, like we have now.

**Comment by Makman2** [comment]
I like to keep this as a reminder, but as @sils1297 stated it's more priority to get functional stuff working, and Windows is "known to work" so it should fit :)

**Comment by AbdealiJK** [comment]
I notice that the appveyor.yml is now relatively empty and the things which I had installed earlier like dbus, espeak, clang aren't there anymore .
Was that done to reduce build time ? In that case do we want to install more things ?

**Comment by Makman2** [comment]
@AbdealiJK I think you've never implemented them :O
 I remember you prototyped something but you said there were problems^^

**Comment by AbdealiJK** [comment]
O.o It does seem so. I wonder where that branch went ...
Ah well, alright.

**Comment by sils** [comment]
wow, @harshit17chaudhary sorry that nobody saw this. If you're still interested, we'd love your help!

**Comment by jayvdb** [comment]
This was partially solved, at least for the coala repo, with https://github.com/coala/coala/issues/3715 (and removal of dbus) .
The bears are still a long way from 100% coverage, which is https://github.com/coala/coala-bears/issues/1415 .

And there are individual issues about many of the bears not install in Appveyor.

https://github.com/coala/coala/issues/562#issuecomment-120842084 - Yes, I encountered the same problems with the clang bears on x64 (only), using clang 3.4.  Other versions of clang completely failed.  I dont have a Windows machine, so couldnt debug.

IMO this issue is best closed, and continued in other issues in the bears repo.
