### ISSUE TITLE
CI errors due to upgraded version of autopep8

### ISSUE THREAD

**Issue by Dhiraj240** [coala/coala#5834]
CI showed following error:
```
!    ! The code does not comply to PEP8.
[----] /home/travis/build/coala/coala/coala
[++++] /home/travis/build/coala/coala/coala
[  16] from coalib.coala import main
[INFO][15:38:29] Applied 'ShowPatchAction' on 'coala' from 'PEP8Bear'.
**** PEP8Bear [Section <empty> | Severity NORMAL] ****
!    ! The code does not comply to PEP8.
[----] /home/travis/build/coala/coala/coala
[++++] /home/travis/build/coala/coala/coala
[  24] from coalib.coala import main
[INFO][15:38:29] Applied 'ShowPatchAction' on 'coala' from 'PEP8Bear'.
**** PEP8Bear [Section <empty> | Severity NORMAL] ****
!    ! The code does not comply to PEP8.
[----] /home/travis/build/coala/coala/tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py
[++++] /home/travis/build/coala/coala/tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py
[   1] from coalib.results.RESULT_SEVERITY import RESULT_SEVERITY
[   2] from coalib.output.JSONEncoder import create_json_encoder
[   3] from coalib.results.SourceRange import SourceRange
[   4] from coalib.results.Result import Result
[INFO][15:38:30] Applied 'ShowPatchAction' on 'tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py' from 'PEP8Bear'.
**** PEP8Bear [Section <empty> | Severity NORMAL] ****
!    ! The code does not comply to PEP8.
[----] /home/travis/build/coala/coala/tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py
[++++] /home/travis/build/coala/coala/tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py
[  10] from coalib.results.Result import Result
[  11] from coalib.results.SourceRange import SourceRange
[  12] from coalib.output.JSONEncoder import create_json_encoder
[  13] from coalib.results.RESULT_SEVERITY import RESULT_SEVERITY
```

Steps to reproduce : 
1.In my local system i installed new version of autopep8 in my virtual environment where i kept coala, coala-bears.
2.Then i ran coala over this repository.
3.Thus got the updated version ```test_external_bear.py```  script and ```coala``` file.

>I doubt whether pushing those updated files here will remove that problem or do one need to change the version of ```PEP8bears.py``` at [this](https://github.com/coala/coala-bears/blob/master/bears/python/PEP8Bear.py#L15) in ```coala-bears``` repositry.
Alternatively [this](https://github.com/coala/coala-bears/search?q=autopep8&unscoped_q=autopep8) link probably for autopep8 versions to ```1.4```

**Comment by Dhiraj240** [comment]
@jayvdb can i work on this? also please check whether this way could produce something valuable.

**Comment by sangamcse** [comment]
The error is due to the new feature in `autopep8`, i.e, `E402 - Fix module level import not at top of file`. You can find many others at https://github.com/hhatto/autopep8#features.

So @jayvdb, we need your view on the `E402`. Should we keep this feature for this repo and make the changes in below 2 files:
1. coala, and 
2. tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py

or do we need to ignore `E402` checks.

**Comment by jayvdb** [comment]
ignoring it requires as much work as fixing it.

ignoring it is as complex as fixing it.

**Comment by agrawalarpit14** [comment]
@bkhanale This is a crucial issue. We need to fix it ASAP!
Let us know if you are facing any kind of difficulty

**Comment by bkhanale** [comment]
@Dhiraj240 @agrawalarpit14 Yes, I got that. I hope this change would fix it:

```
from coalib import assert_supported_version
from coalib.coala import main
import sys

assert_supported_version()

if __name__ == '__main__':
    sys.exit(main())
```

and

```
from coalib.results.Result import Result
from coalib.results.SourceRange import SourceRange
from coalib.output.JSONEncoder import create_json_encoder
from coalib.results.RESULT_SEVERITY import RESULT_SEVERITY
import os
import sys
import json

# Start ignoring PycodestyleBear* as those imports may raise
# import warnings
sys.path.append(os.path.join(os.path.dirname(__file__),
                             '..', '..', '..', '..'))
```

Let me know if its correct. Also I have removed the `#Stop ignoring` comment, I wasn't sure where to place it.

**Comment by jayvdb** [comment]
For the tests/ file, the problem is quite different.

The code is ugly.  The bears are right.  There is no reason for us to be using `sys.path` to help the imports.

The reason it is there, is that `coalib` hasnt been 'installed' before the tests are run, so the exec of `sys.executable` fails when importing coalib.

sys.path is a horrible workaround for that.

One solution is to install coalib before running the tests, but there are good reasons to not do that.

The other is to set environment variable `PYTHONPATH` to `../the/path/../of/coalib`.

That is the correct solution.

Then the sys.path can be removed, and we can stop ignoring the linters.
